### ISSUE TITLE
[MyMeta] Editing a profile doesn't appear to save changes but actually does 

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1228]
### What happened?

I've edited the profile by going to the quick edit page on the profile, made changes & clicked save.
Things changed, but as soon as I've refreshed the page, it reverts to the old.
The weird part is that the changes are actually reflected on self.id...
So maybe has something to do with our caching?
Also probably related to #363

### What did you expect to happen?

I expected the changes to stay.

### How can we reproduce the problem (as minimally as possible)?

Try going to your profile, clicking this
![image](https://user-images.githubusercontent.com/55857222/162419066-87898bbd-9725-4416-b86a-33482c9771fe.png)
making some changes, saving & then refreshing the page..

**Comment by dysbulic** [comment]
The way the system works is it makes the changes to Ceramic and to the local instance, and then signals Hasura to update the data.

If you refresh before Hasura get the new data, you'll see the old. If you refresh again after two or three minutes though, you should see the new data.

The only way to fix this is to load parts of the profile page directly from Ceramic. It means another refactor and some more complexity since some parts, like the DAO memberships and skills, only exist in Hasura.

Do you still see the old data in MyMeta now after an extended delay?

**Comment by peth-yursick** [comment]
> Do you still see the old data in MyMeta now after an extended delay?

Looks like it updated by now & looks like @pvblick-vniversal-friend profile updated as well..
Thanks for the clarification, closing this now. And should I close #363 as well?
