### ISSUE TITLE
vid's xp is stuck

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#1243]
### What happened?

Both total and seasonal xp have been stuck for the past 3 weeks:
<img width="542" alt="Screenshot 2022-04-13 at 16 30 24" src="https://user-images.githubusercontent.com/35112939/163204081-3e3fb169-80e3-49cd-89d3-2ca5a982c5f1.png">

### What did you expect to happen?

xp should keep on changing as it does here: https://xp.metagame.wtf/

### How can we reproduce the problem (as minimally as possible)?

Go to https://metagame.wtf/players or https://metagame.wtf/player/vid 

### Is there anything else we need to know?

My xp is also stuck in my header:
<img width="260" alt="Screenshot 2022-04-13 at 16 32 11" src="https://user-images.githubusercontent.com/35112939/163204031-d5a9d032-a312-4615-909c-7a604c769a9c.png">

**Comment by alalonde** [comment]
I don't think your new eth address was ever updated in the sourcecred ledger.  Have you received any mints at your new address?

**Comment by dysbulic** [comment]
I'm seeing `0x81A8C4Dca0E33c8a46023cc017FFE5938541b0fF` & `0x89bf9BAaeE2d451477CF850fE4c0d89bb796B1aD` for "vid" in [the ledger](https://github.com/MetaFam/XP/blob/master/data/ledger.json) with `0x89…` being the later one.

I'm pretty sure the issue is [`getLatestEthAddress`](https://github.com/MetaFam/TheGame/blob/develop/packages/utils/src/sourceCredHelpers.ts#L5-L8) which uses `find` which returns the first instance that it sees.

If `identity.aliases` is definitely sorted by timestamp, (or is sorted explicitly) then we could do a `reverse` before the `find`, and it should return the latest entry. Alternatively, we could do a `filter` then a `sort` and `slice(-1)`.
