### ISSUE TITLE
[Landing] Small fixes & changes to the landing page

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1313]
Made some fixes & changes to the landing page design mostly based on feedback by designers & users.
If anyone is interested, you can [start going through the updated design](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=5237%3A2386) & implementing the changes as described below.
- [x] Removed the comma from "gold rushing cowboys, & snake oil salesmen"
- [x] Added headers to the pages (should also be renamed on the side menu) as recommended
- [x] Made "the problem" section text narrower, so its not only the word "navigate" that breaks into new line
- [x] Also made the text of the section above a bit narrower so its not so much wider
- [x] Added rainbow color to every bolded word as recommended
- [x] Added a new slide to bridge the transition from "its a wild web" to "we produce content...". Did it by duplicating a slide & zooming in on the image tho we can disregard that part & only make the old text slide out & new text slide in 🤷‍♂️

**Comment by luxumbra** [comment]
This is a great 1st issue! Hopefully a new octo will pick this up but if no-one does, I'll sort it when i get to #1296 in the next few days.

@hhh-gh - this is another issue that you could take on - a few css/chakra tweaks & a bit of javascript required. no worries if you don't have bandwidth or whatever. :)

**Comment by HHH-GH** [comment]
I think I could do most of it, but not totally clear on the new slide and getting the text moving around

**Comment by HHH-GH** [comment]
About the "made the problem section text narrower" one - I used a non-breaking space character to join the words "to navigate", so that "navigate" won't go down to a new line by itself. Doing it the lazy way (:P) meant that there wasn't a need to change the width of "the section above so it's not much wider"

lmk if you'd prefer me to do it the non-lazy way.

![1313-nbsp-and-rainbow](https://user-images.githubusercontent.com/92962228/179883418-833fe042-ecb9-4bb8-9609-13bdb0d8794d.png)

![1313-nbsp-and-rainbow_sm](https://user-images.githubusercontent.com/92962228/179883423-8e67f272-ac6f-4e31-9feb-a53636d0c381.png)

Can you give me some pointers on what you mean by adding the headers? (An example of where they are in use somewhere else in the website? A code example?)

**Comment by HHH-GH** [comment]
The new branch is landing-page-small-fixes-1313, if you want to take over @luxumbra

**Comment by luxumbra** [comment]
> The new branch is landing-page-small-fixes-1313, if you want to take over @luxumbra

Thanks @HHH-GH, I'll take a look at the branch tomorrow hopefully. 🙏🏻 

If you open a PR against `develop`, it'll deploy a preview for visual reviews.

**Comment by HHH-GH** [comment]
> If you open a PR against `develop`, it'll deploy a preview for visual reviews.

Got it - was uncertain if I should wait for more significant changes before I did that. But it's all good to just go ahead and do it straight away?

I would like to have a go at the headers and new slide, but if that would delay everything I'd also be fine to have a look through after you've done the work.

**Comment by HHH-GH** [comment]
Should I change that PR to a draft, as there's still work to do?

**Comment by luxumbra** [comment]
> Should I change that PR to a draft, as there's still work to do?

Yes. Sorry for the delay. :)

**Comment by HHH-GH** [comment]
I think I got 'em all. Check the deployment in the PR at https://github.com/MetaFam/TheGame/pull/1319
