### ISSUE TITLE
[MyMeta] Connect fails for new users on first try

### ISSUE THREAD

**Issue by dan13ram** [MetaFam/TheGame#1351]
### What happened?

When you try to connect with a new ethereum address, the backend tries to create a new player row but this takes some time.

This raises two issues: 
1. The user has to wait for a long time without any feedback on the UI
2. It sometimes fails when this takes too long and you've to refresh to connect properly.

### What did you expect to happen?

The connect shouldn't fail for new users => Very Important.

Maybe we restructure the connect flow for "new" users by giving more feedback on what's happening in the background.

### How can we reproduce the problem (as minimally as possible)?

Connect with a brand new ethereum address. 
Or locally login with an ethereum address that is not in the db by removing it.

### Is there anything else we need to know?

Nope.

### Browser and operating system used (if applicable)

Brave browser on Ubuntu

**Comment by dysbulic** [comment]
Ok, I tried the site with an account not in the system.

When I first hit connect, it asked me in my wallet if I trusted MetaGame, then it got stuck on a "Connectiing" loading spinner. There was no errors in the console to indicate where it got hung up.

After I reloaded the page I was still unable to connect because I kept getting the error, "No signer found for this account".

I thought it might be something to do with me using Frame as my wallet, but Frame was a recognized option in `WalletConnect` when it asked me which wallet to use.

There is a more fundamental issue at play that might be related to this…

The first time a user account is requested from Hasura, if it doesn't exist it will be created. There are a couple of simultaneous processes that can request an account, and so multiple requests for a new account can arrive simultaneously. When this happens, the first will generate a new account and get an id to pass back, and the others will fail because they'll try to create an account and there can only be one for a given ETH address.

To avoid this, there is a check in the system for if there's an active process generating a new account, and if there is a request will wait for that to complete before trying again to look the user up.

The current implementation is using a n exponential backoff `wait` function to pause execution. There is a more effective way to write the logic using a native JavaScript flow control mechanism called `Promise`s. I need to revisit this, I've just not had the time to sit down and bang out the new code.

It might have an effect on the login process.
