### ISSUE TITLE
'Pool info' link in the dashboard goes to the mainnet pool

### ISSUE THREAD

**Issue by luxumbra** [MetaFam/TheGame#1407]
### What happened?

I clicked the pool info link and was taken to the old pool on mainet that we are winding down. 

### What did you expect to happen?

I expected to go to the pool on polygon.
https://polygon.balancer.fi/#/pool/0x8a8fcd351ed553fc75aecbc566a32f94471f302e000100000000000000000081 

### How can we reproduce the problem (as minimally as possible)?

Got to the [dashboard](https://metagame.wtf/dashboard) and click the 'Pool info' link in the Seed block. 
![image](https://user-images.githubusercontent.com/780350/195473704-5b8a234b-2eeb-46ae-bc40-bd9eee2d12e9.png)

**Comment by HHH-GH** [comment]
So I thought this was going to be an easy URL update 😂

Here's where the link comes from: [components/Dashboard/Seed.tsx](https://github.com/MetaFam/TheGame/blob/ae0102b3ade3cd5c94b378bdfac4a7e8a87c5522/packages/web/components/Dashboard/Seed.tsx#L171)
```
href={token?.poolTicker.token_info_url}
```
`token_info_url` comes from an [API call to Coingecko](https://api.coingecko.com/api/v3/coins/metagame/?localization=false&tickers=true&market_data=true)

Looking at the JSON from the API call, there's a ticker entry for the Mainnet pool. (See `token_info_url` near the bottom)

![image](https://user-images.githubusercontent.com/92962228/200795789-f2206bec-8a64-4017-9ff8-b6adf49b8ef5.png)

In the Discourse I saw some discussion on [getting Coingecko to include Polygon data](https://discord.com/channels/629411177947987986/756495271344603226/990949512476512297)

If the Pool Info link is to come from the Coingecko API, then this issue is stuck until the Polygon data is added to Coingecko.

(Also - does this mean the Seed info on the dashboard [market price, lows, highs, etc] is actually for the Mainnet Seeds?)

**Comment by HHH-GH** [comment]
Options for this one
1. Hard code the pool link instead of getting it from the Coingecko API (fairly easy)
2. Ask Coingecko to update their info (send them the new data, wait for them to update? not sure how that works)

Is there a preference? @peth-yursick    @luxumbra

**Comment by luxumbra** [comment]
> (Also - does this mean the Seed info on the dashboard [market price, lows, highs, etc] is actually for the Mainnet Seeds?)

Yes, I believe it is all coming from the mainnet pool. I *think* I contacted CoinGecko a few weeks ago to ask them to change to our Polygon pool but not 100% if i did in the end. Will check & chase or send a request if I only imagined doing it before. 

> Hard code the pool link instead of getting it from the Coingecko API (fairly easy)

I think for now, this is the best option - gets it fixed pronto and we can re-visit once CG have updated things their side.

**Comment by HHH-GH** [comment]
I've just done some investigating.  
1. The current price for all versions of Seed seems to be 1 Seed to 3.8 USD. (See below. I also have screenshots.)
2. So I can't tell if the Coingecko API is returning info for the Mainnet pool or the Polygon pool.
3. But also the [Coingecko API](https://api.coingecko.com/api/v3/coins/metagame/?localization=false&tickers=true&market_data=true) is not (currently?) providing the ticker info that included the `token_info_url` that was used to create the link, so the dashboard is not linking to either the Mainnet or Polygon pools.

I'll add some temporary code to hard-code the pool link for now, and we can revert it when/if CG updates.

---
```
Seed price on Coingecko............3.79 USD
Seed price on the CG API...........3.8  USD
Seed price on Balancer (Polygon)...3.8  USD
Seed price on the dashboard........3.8  USD
Seed price on Polygon scan.........(no data)
```
