### ISSUE TITLE
[Quests] Improving Quests

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1422]
On the quests list view:
- [x] Make whole cards clickable, like on /players & /patrons
- [x] Fix bottom row card height (currently appears higher for some reason)
- [x] "Skills" & "Roles" should be at the bottom of the card, regardless of the size of the description. Either that or the description should be a fixed number of rows but @luxumbra mentioned a problem with that I can't recall.
- [x] Change the default number of quests loaded to 50
- [x] Move "read more"
- What it will look like:
![image](https://user-images.githubusercontent.com/55857222/206423644-74ced4fb-b0ee-4e2f-936b-029cbd456f94.png)

Inside the quests:
- [x] Fix the card cutoff
- [ ] Add an option to delete quests
- [ ] Increase the size of the "description" box when submitting a quest completion. Right now its a single row.
- [x] There's a weird bug of the creator card getting cut off when under the effect
- [x] Also the creator card looks much narrower than on /players or /patrons - should be the same cards
- [ ] Change the placement of the "claim" button
- [ ] Change the placement of "edit" & "open link" buttons
- [x] Get rid of one of the titles (currently quest title is displayed twice)
- [x] Design & implement the "back to quests" button
- [x] Change the "created by" card to reuse the same component from /players (currently seems hardcoded & different aspect ratio, taller & narrower than on /players, /patrons or /guilds)
- [ ] The "You Gain" aka Reward section should maybe be separated from the description & based on guilds (eg. if the quest is for MetaFam, then it should be that. Currently needs to be copy/pasted to the bottom of every quest & also takes a fair chunk of the description)
- [ ] Have a designer look at the overall design & see what else should be improved
   - [ ] eg. having a side box or something that displays "you gain"

Outside:
- [ ] Making URLs actual names of the quests rather than hashes
- [x] Make sharing URL surface the quest image rather than MG logo

**Comment by tommycomma** [comment]
It would also be helpful to have a share icon on each card and/or if the URLs are the names of the quests

**Comment by HHH-GH** [comment]
I'll be working to this design for the Quest Explorer and View pages.

https://www.figma.com/file/2yEeQUrgPOrLOq6DpC6Mb7/Quests-UI?node-id=506-2078&t=KoBXzpAaD72HLMQQ-4

Rough plan
1. Do the Quest Explorer view basics
2. Do the Quest Details view basics
3. Trigger a preview build to use a a base for discussion on the rest of the task

**Comment by HHH-GH** [comment]
**Progress update**
- Whole cards are clickable (although there was a bit of messing about to avoid hydration errors caused by links inside the quest descriptions)
- Fix bottom row card height—the cards should all be the same height as the tallest in each row, and with the description limited to 4 rows of text they should all end up the same height each time
- Skills and Roles tags are aligned to the bottom of each card
- ~~Move~~ DELETE read more—the whole card is clickable now, matching the other cards (which don't have read more), and carving out a little gap for a read more link in that spot is probably not realistically doable.
- Quest Explorer page matches @davort design

**Next**  
- Load 50 quests by default in the Explore Quests list
- Quest Details page updates

I'll start a PR when there's a bit more to look at.

**Comment by HHH-GH** [comment]
**Progress update II**

- 50 quests are loaded by default (*I think*, because the test data only has 4 quests. TODO: check later)
- Quest details page: basic structure of the page is done, TODO put live data in it

**Comment by peth-yursick** [comment]
Awesome, thank you for reporting!
Other than having more load from the outset, it would be good to have them auto-load further like on the players page or to have a "load more" button at the bottom. Tho there's only like 20-something quests on there so not a n important feature to have right away.

Also, might be good to hide "date created" for quests at least for now - some people see its been created 9 months ago & they think the quest is inactive or sketchy esp. if there's 0 submissions after 9 months..

**Comment by HHH-GH** [comment]
> Also, might be good to hide "date created" for quests at least for now - some people see its been created 9 months ago & they think the quest is inactive or sketchy esp. if there's 0 submissions after 9 months..

I'll have notes about this (and more) for the next step. There are quite a lot of things like this that aren't covered (yet?) in the new design, and I'll write them up to discuss with Dave.

**Comment by HHH-GH** [comment]
**Progress update III**

It's now mostly matching @davort design. Last bit on that is making the text of the quest description match the sizes/spacings/etc of the new design. I'll start a PR after that so you can get a look.

In Progress Update III:
- Make sharing URL surface the quest image rather than MG logo ✔
- 'Created by' card and related - this was removed from the new design, so ✔?
- Back to quests button ✔
- Get rid of one of the titles ✔

**Comment by HHH-GH** [comment]
Done the typography. Now starting a draft PR so you can get a look at it.
