### ISSUE TITLE
Leaderboard is making dozens of graphql requests

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1482]
### What happened?

The leaderboard takes a very long time to load. This is probably because it is making a separate graphql request for every (visible?) player:
```
guild_player(where: { playerId: { _eq: $playerId } }) {
   ...
}
```

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/1402582/207937456-8c6057ca-dc12-432d-9698-e4d6425b8431.png">

### What did you expect to happen?

The leaderboard page loads reasonably quickly

### How can we reproduce the problem (as minimally as possible)?

Go to the leaderboard and open the developer tools > network tab

**Comment by peth-yursick** [comment]
👌
This should close #1200

**Comment by dysbulic** [comment]
I'm thinking about using [react-query](https://tanstack.com/query/v4/docs/react/examples/react/load-more-infinite-scroll) to handle synchronizing with the server state.

It's a library I've heard nothing but good things about & at the very least it won't be less performant than what we've got currently.

**Comment by dysbulic** [comment]
@alalonde, after refactoring things to make a single request for the player information, I recognize that the way it was was better.

The dozens of requests that you are seeing are the queries for the DAOHaus memberships for each player. These are loaded separately from the main player object because retrieving each one requires a `fetch` to the DAOHaus metadata server.

I'm still figuring out how everything's stitched together. It looks like there's a caching table called `Daos`, but it doesn't seem to be being used.

*I put a print statement in the backend code before the `fetch` for DAO metainformation, and I'm seeing it printed for every user requested.*
