### ISSUE TITLE
Fix XP accumulation to match current rewards systems

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1551]
### What would you like to be added?

[TBD](https://forum.metagame.wtf/t/nexp-whats-next-for-xp/1122), but probably just pull players' SEEDs from polygon and compute XP from the monthly distributions

### Why is this needed?

The current XP / leaderboard is solely based on Sourcecred which is only half of the MG value attribution. Moving forward there will be XP accumulated from Coordinape.

**Comment by dysbulic** [comment]
What I'd really like is a per-user Ceramic stream that has their current XP in it.

Unfortunately, I [asked on Ceramic's Discourse](https://forum.ceramic.network/t/is-it-possible-to-programatically-update-a-model-associated-with-a-user/842/2) and they said the model they'd like me to use is the User owns the stream and gives permission to the server to write to it.

That's not really what I want since I don't want users to be able to update their XP value.

Apparently if the server owns the streams there's no way to look up the stream for a user, without delving into the SQL backend…

**Comment by dysbulic** [comment]
So, Ceramic released a [filtering and querying framework](//blog.ceramic.network/tutorial-query-filtering-and-ordering-in-composedb/). I [asked](//forum.ceramic.network/t/sorting-on-a-combination-of-multiple-streams/1278/1) whether we could use this to generate the leaderboards straight from Ceramic, but the answer was "no".

**Comment by Seroxdesign** [comment]
https://github.com/MetaFam/TheGame/issues/1586
