### ISSUE TITLE
Improve Guild Data in Profile

### ISSUE THREAD

**Issue by Seroxdesign** [MetaFam/TheGame#1607]
### Feature

We would like to improve the guild membership data in accordance to the following designs:

Design Issue:
https://github.com/MetaFam/TheGame/issues/1539

Figma:
https://www.figma.com/file/vzrD9jHcKv2T5V8ikrGtUu/Improve-guild-membership-data?type=design&node-id=356-7242&mode=design

Steps:

1. Allowing users to search for and hide, add and remove Guilds from their profiles:
   
   - If Guild has verified user membership, place a verification check - green
   - If Guild rejects membership request, place a rejected check - red
   - Otherwise leave an empty badge - grey
   
2. Create a guild admin role, which will be able to maintain and edit guild data:
   In the context of this specific task we will need the admins to be able to:
   
   - Add new members to their guild
   - Verify or reject membership requests
   
3. Create membership sub-page example: metagame.wtf/guild/hunters-worskshop/members:
   In this page we would like to display the same data as the /players page, but only for members of the specific guild
   
![image](https://github.com/MetaFam/TheGame/assets/69639595/22ac3519-261b-423e-bfb2-68af12a9413d)

4. Make XP Leadboard a choice in the edit guild membership for admins.
   In this task we will show a leaderboard with 0 values of whatever the guilds token/xp/share is
   
5. In member's profile, show the guilds token/xp/share for the guild membership.

### Why is this needed?

This is for the composeDB grant

**Comment by peth-yursick** [comment]
The part about manually reviewing membership seems unnecessary..
"Verified" is already automatic in 2 ways: DAOhaus DAO membership (currently broken) & discord member (based on roles).
The point of the issue was to allow people to add guilds that don't have a DAOhaus DAO & aren't members of MetaGame, this is accomplished in the design by user manually adding the guild as "unverified".
If they want it to be verified, the guild has to join MetaGame. If the guild joins MetaGame, it should automatically verify like others, so why the manual reviewing process?

**Comment by alalonde** [comment]
Closing this in favor of #1561
