### ISSUE TITLE
Introduce State Management Library

### ISSUE THREAD

**Issue by Seroxdesign** [MetaFam/TheGame#1611]
##

I would like a state management library to be added to the frontend repo, as things stand there are many component that have shared state/data that cannot be automatically updated and reflected without refreshing the site 

**This goes against React's architecture, we should never have to refresh to see updated**

State management libraries to choose from:

https://blog.openreplay.com/top-6-react-state-management-libraries-for-2022/

### Why is this needed?

Too many components impossible to pass around state, and Hasura cache prevents easy queries

**Comment by alalonde** [comment]
IMO we should just fix the underlying issue rather than add another level of complexity via a state management layer.  Since we have data coming from two sources (Hasura + composedb), our [current method of caching](https://formidable.com/open-source/urql/docs/basics/document-caching/) is insufficient.  I started looking into [this](https://formidable.com/open-source/urql/docs/graphcache/) while doing the composeDB migration, but didn't implement it for fear of delaying everything else. Or we could just switch off of urql entirely..
