### ISSUE TITLE
Update Database Schema for new profiles setup

### ISSUE THREAD

**Issue by hammadj** [MetaFam/TheGame#25]
Simplify the DB schema to only the essentials we need for profiles

**Comment by pakokrew** [comment]
Proposed modifications in schema :

**Player**
- id
- username
- totalXp
- rank (remove, calculated from totalXP)
- links (remove, get it from linked accounts)
- sentences (remove)
- guilds_member > (?)
- quests_completed > (?)
- XPIntervals > (?)

From the wireframes, we should add:
- role
- timezone
- enneagram profile
- skills

I didn't add availability since I don't think we'll be able to ask to hire right now.
Name, profile picture and about me are inside 3Box

**Accounts**
- player_id
- identifier
- linkToProof (remove ?)
- type


Do we keep Guilds, Quests, XPInterval ?

**Comment by hammadj** [comment]
@pakokrew Link to proof comes from 3box as well, they have github/twitter in there, but yea dont need to have it in our DB, can just use remote join.

For guilds, I think we should still h
