### ISSUE TITLE
[MetaOS] Make apps open below the navigation board

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#269]
The idea with the MetaOS is bringing all the disparate pieces of MetaGame into a unified interface, which is why its absolutely crucial that the apps are opening below the mega menu rather than in new tabs.

How it would look:
You open the menu & click the wiki
![image](https://user-images.githubusercontent.com/55857222/142192745-54573412-0c08-4045-a1af-70888467ca76.png)
The wiki just opens below, instead of in a new tab
![image](https://user-images.githubusercontent.com/55857222/142192956-2d869926-3856-44ef-83a3-71eefc96f4ad.png)

How it could work:
To begin with, we can start with simple iframes.
Going forward, we'll be creating custom UIs & micro-front-ends for most used dapps & apps.
Eventually, people should be able to compose their dashboard as a mosaic of windows into different apps.

What about mobile???
- On mobile, we can just have apps open in full screen but add a "return to home" button to go back to the dashboard.

Maybe start with this one #272?

**Comment by geleeroyale** [comment]
could not finish because I never got it to run in the metagame site structure - was always colliding with some internal thing.

However - someone more familiar with app architecture might have a go - its quite simple actually.

(and at some point I would love an intro or a mention in the docs on how to actually **add effin dependencies**

https://codesandbox.io/s/react-mosaic-2dloh?file=/src/App.tsx

**Comment by sunguru98** [comment]
@geleeroyale, may I take this a look please?

**Comment by pakokrew** [comment]
While working on the questing system, I had to dive deeper into server-side rendering, nextjs, urql and how these three interacts, and makes me think this window will not be trivial to integrate.

### Why we have SSR/NextJS
Server-side rendering makes web pages load all-at-once super quickly, as opposed to client-side SPA which takes a while to render on users screens, with renders cascades, loaders & stuff.

In addition to make pages display quicker, it also adds an invaluable advantage for SEO: pages are pregenerated and can be indexed by search engines. Dynamics routes like https://my.metagame.wtf/player/peth-yursick would never appear on Google if the app were build with pure client-side React.

I don't say being indexed by search engines is a must have, but @hammadj made the decision to use this architecture and our whole (already quite big) app is built on top of that.

### Why window system is hard to integrate here

Window system is by design dynamic, i.e. custom to each user, so can't be pre-generated. 
They also void the traditional routers (why would we navigate to `mymeta.wtf/player/peth` when we have all windows accessible in `mymeta.wtf` ?), which in turns void our pre-rendering system, then indexing capabilities. 

In NextJS, you define pages, and you define which data is needed for each of these pages. 

### What could be done

I'm not saying it's impossible, here what we could do:

Having our main app in `/`, which opens the window system. Keeping all the others pages for indexing, automatically populate the window system with the page loaded and it's loaded data.

**Comment by pakokrew** [comment]
Thinking out loud here but maybe we could:

Keep our system as it is now

Create one special page which implements windows system, that opens our own pages in iframes (`mymeta.wtf/player/peth`) with a query (`?embed=true`) which disable headers, menu etc to be embed.

So we keep both of two worlds. App navigable normally as before, and for geekys persons that wants multiple pages on one, they go on this special page.

**Comment by geleeroyale** [comment]
unassigned myself - @dan13ram will probably pick it up

**Comment by geleeroyale** [comment]
Saving my work in progress here. Made this little component that needs typescript cleanup to be pushed - made as `/pages` component:

```typescript
import React from "react";
import { Mosaic, MosaicWindow } from "react-mosaic-component";

import MetaWiki from "../components/Windows/MetaWiki.js";
import Calendar from "../components/Windows/Calendar.js";
import MetaRadio from "../components/Windows/MetaRadio.js";
import SeedPool from "../components/Windows/SeedPool.js";

import "react-mosaic-component/react-mosaic-component.css";
import "@blueprintjs/core/lib/css/blueprint.css";
import "@blueprintjs/icons/lib/css/blueprint-icons.css";


export type ViewId = "a" | "b" | "c" | "new";

const config = {
};

const APP_MAP: Record<ViewId, string> = {
  a: <MetaWiki/>,
  b: <SeedPool/>,
  c: <MetaRadio/>,
  new: "New Window"
};

const width = '100%'
const height = '100%'

export const mosaicWindow = (
  <Mosaic<ViewId>
    className="mosaic-blueprint-theme bp3-dark"
    renderTile={(id, path) => (
      <MosaicWindow<ViewId>
        config={config}
        path={path}
        createNode={() => <Calendar />}
        title={id}
      >
        <div style={{ width: `${width}`, height: `${height}`, scrollbarWidth: 'none' }}>{APP_MAP[id]}</div>
      </MosaicWindow>
    )}
    initialValue={{
      direction: "row",
      first: "a",
      second: {
        direction: "column",
        first: "b",
        second: "c"
      }
    }}
  />
);

function WindowManager() {
  return mosaicWindow;
}

export default WindowManager;
```

This is the component used for the window manager: 
https://github.com/nomcopter/react-mosaic

And ... salvaged from chat (thanks Peth!) - the mock-ups for the actual window manager:
https://www.figma.com/file/yFjwnlldaEhPOEls3rz18t/OS-Window?node-id=86%3A107

**Comment by peth-yursick** [comment]
There's this as well #227

**Comment by vidvidvid** [comment]
I implemented iframes for most of the items from the megamenu, check out the PR: https://github.com/MetaFam/TheGame/pull/960

**Comment by peth-yursick** [comment]
> I implemented iframes for most of the items from the megamenu, check out the PR: #960

omg omg omg omg

**Comment by peth-yursick** [comment]
lmk when merged, I can't wait to test & finally close this issue

**Comment by vidvidvid** [comment]
@peth-yursick _merged_

**Comment by vidvidvid** [comment]
just to develop branch, though
