### ISSUE TITLE
[MetaOS] Different upon login

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#317]
Heterotic and I talked about adding more "apps" to the app drawer, but concluded the ones we wanted to add are the ones that are supposed to be there only upon login.

We should probably figure out what to base the login on. It should happen after a person connects a wallet, but its an open question on whether the access should be based on Seeds, pSeeds or something else entirely (an access key NFT?)
I'd say probably an access NFT because new players won't have Seeds nor pSeeds, but it makes it more complicated because then we need another step in the onboarding process where we mint a key for a newcomers and send it to them.

Thoughts?

**Comment by dysbulic** [comment]
So these are applications that only Players are supposed to have access to?

An alternative to a NFT is a [Verifiable Credential (VC)](https://www.w3.org/TR/vc-data-model/) denoting that a particular DID is a Player of MetaGame. VCs are part of the W3C's Self-Sovereign Identity (SSI) structure. It is a signed JSON object that describes the characteristics of a [Decentralized Identifier (DID)](https://www.w3.org/TR/did-core/).

The VC could be stored at a fixed location in their Ceramic Index. When MetaOS loads is checks the Index and if it finds an appropriate VC it enables the restricted applications.

Better than that would be [Capabilities Documents](https://w3c-ccg.github.io/zcap-ld/) giving the user's DID access to the different applications. Capabilities allow you to specify what a user can do as opposed to operating based on who they are. [Everything I've read](http://waterken.sourceforge.net/aclsdont/current.pdf) suggests that Capabilities are superior to Access Control Lists in securing an application.

These documents could also be stored in the [metadata for a NFT](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md#user-content-specification:~:text=metadata%20extension,-is) rather than in Ceramic.

Do you envision users being able to transfer their capabilities (or player status) to other accounts? Associating the information with an NFT makes that easier.

To some extent, putting the information on-chain tells the world who has keys to access your app and makes those people subject to attack, particularly when combined with MyMeta which provides an in-depth profile for the would-be target.
