### ISSUE TITLE
[Raids] Raids definition (Draft)

### ISSUE THREAD

**Issue by pakokrew** [MetaFam/TheGame#455]
Once first iteration of quests completed, we need to add a layer on top of it: Raids

Raids are groups of quest. Think of an Epic, splitting the work in different tasks.

## Objective

We first try to create a simple system for replacing the #quests channel in discord. This will implement the Phase 0 we describe in Notion. 

- Only people holding at least 100 pSEED (seeds in liquidity pool) will be able to create raids
- Creation of a **Raids Explorer** page, which redirects to the Quest Explorer filtered on these quests.
- Creation of a page to create a raid
- Creation of a page to edit a raid, only accessible by raid creator
- Edit quest explorer to be able to filter by raid
- Edit quest creation page to optionally select a raid to include it inside
- Edit quest pages to display which raid it is associated to

### /raids

Page displaying all the existing raids.

Filterable by:
- status
- guild
- created by me

Sortable by:
- created_at

On click on a raid, redirect to `/quests?raid_id={raid.id}`

### /raid/new

Creation of a raid. 

### /raid/{raid_id}/edit

Page to edit a raid. Only available to raid creator.

### /quests

Make the quest explorer load search params from the URL query. via `/quests?raid_id={raid.id}`

### /quest/[id]

Display raid

### /quest/create

Optionally link to a raid

### /quest/[id]/edit

Allow to change raid associated

### raid

id - UUID 
created_at - date, now()
guild_id - UUID , not null
created_by - UUID , not null

title - text, not null
description - text
external_link - text

status - enum [OPEN, CLOSED]

#### Relations

guild_id => guild.id
created_by_player_id => player.id

#### Permissions

- public
SELECT *
- player
SELECT *
UPDATE [title, description, external_link, status] where (User-Id === created_by)

### raid_quest

raid_id - UUID , not null
quest_id - UUID , not null

#### Relations

quest_id => quest.id
skill_id => skill.id

#### Permissions

- public
SELECT *
- player
SELECT *
INSERT * where (User-Id === quest.created_by)
DELETE where (User-Id === quest.created_by)

#### Create raid

Check if player is holds more than 100 pSEED, and create the raid.

We need to create a function to bypass hasura permissions, to check who is allowed to create raids.

**Comment by peth-yursick** [comment]
🔥🔥🔥
The only thing I'd do differently is make it so that a player needs to hold 200 or even 300 pSeeds?

The quest creation requires 100, so I think it would make sense that raid creation requires more.
Also, with 100 pSeeds at the current rate, a malicious actor only needs to plant ~$3k worth of Seeds to troll MetaGame 😬
I'd argue it should require even more. The main thing would be to make it so that "raid creation" starts a step before the "create raid" button.
We could start with the forums for now, but eventually, there should probably be a "propose a raid" button that anyone can click & fill out regardless of how many pSeeds they have.
The raid proposals would then wait for community signal, which would compel large pSeed holders to "make it official". 
Or make it start automatically after enough community signal?
Or we could make it so that anyone can start it, but the community signal can cancel it?
Definitely something that should be discussed more in-depth. 
We should also sync up with Sourcecred & see how their initiatives plugin is going. Need to get @hammadj on this thread.

But yeah, that's my main concern.
Other than that, you & @dysbulic should probably work together & make it so that his raid map & your raid explorer work nicely together :D

Let's discuss about all of this on Wednesday? We're getting back on the regular call schedule, so some of us will be down there in the #dungeon at the usual time: 9am PST / noon EST / 4pm UTC / 6pm CET
