### ISSUE TITLE
[MyMeta] xDAI & Polygon DAO names

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#838]
Right now all the xDAI & Polygon DAOs are displayed as "unnamed".
We need to figure out a way to put their names up..
Could be done through the DAOHaus API maybe? Or DeepDAO if not?

**Comment by dysbulic** [comment]
DAOHaus used to have the DAO name on-chain which is why older DAOs don't show up as nameless.

The name has since moved to a metadata file that is downloadable from a DAOHaus server.

Currently we are querying The Graph each time we load the player's profile. The process of downloading a file and extracting the name for each DAO is too resource intensive to do on each query, so we will need to add a cache of DAO metainformation to Hasura.

**Comment by peth-yursick** [comment]
> 
> 
> DAOHaus used to have the DAO name on-chain which is why older DAOs don't show up as nameless.
> 
> The name has since moved to a metadata file that is downloadable from a DAOHaus server.
> 
> Currently we are querying The Graph each time we load the player's profile. The process of downloading a file and extracting the name for each DAO is too resource intensive to do on each query, so we will need to add a cache of DAO metainformation to Hasura.

Is this a hassle to do? I can reach out to DeepDAO & ask for their API, they already offered it before.

**Comment by mquellhorst** [comment]
Connected to #646 & #997
