### ISSUE TITLE
Non-mainnet DAO memberships don't render properly on the setup / memberships page

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#863]
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/1402582/137573467-341d6549-f4e3-499e-91a2-4f575f96645d.png">

**Comment by alalonde** [comment]
Ah, yes, he would need to be a member of at least one non-mainnet DAO to reproduce the problem.

**Comment by Udit-takkar** [comment]
Not a frontend bug because the response is returning title as null
`{"data":{"getDaoHausMemberships":[{"id":"0x775424aa01a1f4af57a53312f2599a8404024328-member-0x759bace429553bca40645da3283de1a105531b11","moloch":{"id":"0x775424aa01a1f4af57a53312f2599a8404024328","title":null,"version":"2.1","chain":"xdai","__typename":"Moloch"},"__typename":"Member"}]}}`

**Comment by Udit-takkar** [comment]
Or we can do the same here what we are doing in `player/[username]` to display membership like  {title || `Unknown ${chain} DAO`} if not available.

**Comment by alalonde** [comment]
Yeah, let’s just do that so at least they are consistent. The real fix is getting the proper metadata from Daohaus. I believe there’s a ticket for that

**Comment by Udit-takkar** [comment]
<img width="1440" alt="Screenshot 2021-11-01 at 11 09 51 PM" src="https://user-images.githubusercontent.com/53316345/139715538-07f8292e-5019-4988-81b3-a86f5e3b8aba.png">

It would look this this . should i also add image and link to the dao ?

**Comment by alalonde** [comment]
That’s definitely an improvement. If you can get an image and link that’d be even better, just add it to both places

**Comment by alalonde** [comment]
See https://github.com/MetaFam/TheGame/issues/646
