### ISSUE TITLE
Github username not appearing in MyMeta Profile

### ISSUE THREAD

**Issue by tenfinney** [MetaFam/TheGame#877]
## Issue
**github username not showing in profile.**

## Facts
I did not include my Github username when using the profile set-up wizard at https://my.metagame.wtf/players. I did however include my twitter profile and that shows up as expected (see image).

I now want to add my Github username to my profile. I added it to my self.id account where MyMeta properly queries and shows my profile text and avatar image, but no Github username.

## Ideas of what may have caused it:
I suspect this; because I did not assign a Github username in the initial wizard, it is not querying (or maybe it is, but it is turned off to show in the UI) for my Github username from **self.id**, thus not populating the user profiles.

No hurry here; just wanted to document it.

![github-user-profile](https://user-images.githubusercontent.com/32429716/138463988-b568d6cf-32f9-4a8a-833d-44e435c3cefb.png)
.

**Comment by dysbulic** [comment]
This is likely because the system is currently using the legacy 3Box attestations of account ownership. They need to be migrated to [Glaze's 
Also Known As definitions](//github.com/ceramicnetwork/CIP/blob/main/CIPs/CIP-23/CIP-23.md) eventually.

Currently, only the GitHub attestations are working on [self.id](//self.id). Twitter is present, but not functioning.

The ultimate goal is for [IdentityLink](https://github.com/ceramicstudio/identitylink-services) to be the source of truth as to Discord account ownership rather than the bot that is used currently. [DNS.xyz](//dns.xyz) is theoretically going to be running a verifier for all the available services: Discord, Discourse, GitHub, and Twitter, but it isn't up yet and the timeline is uncertain.

Alternatively, we could run an instance of our own. I'm uncertain on the setup complexity, or what the costs would be like.

It is written as a set of AWS serverless functions.

**Comment by tenfinney** [comment]
Cured
![fixed](https://user-images.githubusercontent.com/32429716/141715383-be12d91c-ec05-431b-8ca6-24a2f747d489.png)
.
