### ISSUE TITLE
Standardize guild onboarding copy

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#896]
### What would you like to be added?

We currently have [this Notion page](https://meta-game.notion.site/Guild-Onboarding-Why-How-e3d7383d86de4f7f8240a20cd92b8efb) discussing Guild Onboarding. A lot of this content should probably be in our _actual_ guild onboarding page in [MyMeta](https://my.metagame.wtf/join/guild). This will require some design work and copy work.

### Why is this needed?

Because potential new guilds should have more context about joining: why, if they're a good fit, etc.

**Comment by davort** [comment]
@alalonde - I can take on the design part of this quest!

Just a few quick questions:

1. Are we thinking a "one-page" design, where all the information from Notion is laid out in a readable fashion? Or something else? 
2. Any good examples to draw inspiration from?
3. Is this the page which will open when "For Guilds" is selected from https://wiki.metagame.wtf/?

**Comment by Gnomeski** [comment]
How would you lke copy adjstments/suggestions made? 
I would maybe break it down into: 

- **Technical Alignment,** Ethereum and Web3 already covered.
-  **Social Alignment** ie talking about hierarchies only existent for organisational reasons, not about power-over, authority etc, Importance of diversity, inclusiveness, accessibility, ID some of major issues we are looking to tackle here.
- **Political/philosophical Alignment**: The reasoning behind our Social Alignment agenda, a desire to develop it further etc 
- **Financial Alignment**: 2 paths of Crypto type stuff. Community focused tkns, future tkn/trade bridging desire, co-operation via money markets as  future aim ie growing to have all elements of ther metafactory operating in some way in a decentralised 'marketplace' or simply favour4favour agreements as collaborators for the commons/human centred organisations (DAOs). 

Seeking more clarity over what exactly we are offering after all the doing Good and Podcast etc is completed.. We are acting in an advisory/support capacity then. Providing advice and.or links/connections/networking.. ?  We then are 'open to trade' in terms of being 'operators for hire' to actually work on their DAOs etc? How this works ie Sourcecred etc? Meanwhile who is building MetaGame etc? Are we offering as hack squad for a fee for example a bit like RG? 

Anther question is, altho not on the agenda or required for this copy piece (which already seems pretty good , without any of my comments tbh)  can we eventually extend our Sourcecred set up and the use of SEED to other communities which do not have a tkn? In order to get these privelidges and trust how long would they have to be a member and criteria for that.. oh shit am going on again! lol

**Comment by junkmail-taken** [comment]
I'd like to echo this - 
I think if we evaluate workflows and designated roles below would be useful as roles can change / evolve.  

Also, structuring PR "tools" used as a stand alone for revision and case evaluation relative to a version.  

Template for PR can be created developed once a definition of workflow is structured.

**Comment by alalonde** [comment]
>     1. Are we thinking a "one-page" design, where all the information from Notion is laid out in a readable fashion? Or something else?

Yes, I think it should probably a more concise version of the wiki page.

>     2. Any good examples to draw inspiration from?

... no 😁 

>     3. Is this the page which will open when "For Guilds" is selected from https://wiki.metagame.wtf/?

No, I think there will just be a CTA in that existing wiki page directing them to this new (well, improved) MyMeta page

**Comment by alalonde** [comment]
> How would you lke copy adjstments/suggestions made? I would maybe break it down into:
> 
>     * **Technical Alignment,** Ethereum and Web3 already covered.
> 
>     * **Social Alignment** ie talking about hierarchies only existent for organisational reasons, not about power-over, authority etc, Importance of diversity, inclusiveness, accessibility, ID some of major issues we are looking to tackle here.
> 
>     * **Political/philosophical Alignment**: The reasoning behind our Social Alignment agenda, a desire to develop it further etc
> 
>     * **Financial Alignment**: 2 paths of Crypto type stuff. Community focused tkns, future tkn/trade bridging desire, co-operation via money markets as  future aim ie growing to have all elements of ther metafactory operating in some way in a decentralised 'marketplace' or simply favour4favour agreements as collaborators for the commons/human centred organisations (DAOs).
> 
> 
> Seeking more clarity over what exactly we are offering after all the doing Good and Podcast etc is completed.. We are acting in an advisory/support capacity then. Providing advice and.or links/connections/networking.. ? We then are 'open to trade' in terms of being 'operators for hire' to actually work on their DAOs etc? How this works ie Sourcecred etc? Meanwhile who is building MetaGame etc? Are we offering as hack squad for a fee for example a bit like RG?
> 
> Anther question is, altho not on the agenda or required for this copy piece (which already seems pretty good , without any of my comments tbh) can we eventually extend our Sourcecred set up and the use of SEED to other communities which do not have a tkn? In order to get these privelidges and trust how long would they have to be a member and criteria for that.. oh shit am going on again! 🙄

These are all good questions, and probably worth discussion with the greater community.  To keep this moving, I'd say just take what is already in that wiki page and condense it a bit

**Comment by peth-yursick** [comment]
Here's the updated version of the copy, still too long but about 10% shorter & now with 70% less cringe!
https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=4723%3A2188

**Comment by vidvidvid** [comment]
Heyo, I'll implement this - I need to take a break from calendars and timezones. 😅

**Comment by peth-yursick** [comment]
> Heyo, I'll implement this - I need to take a break from calendars and timezones. 😅

One one hand, I'd leave this to newcomers because it's a good first issue & we've received feedback from newcomers that there aren't enough meaningful good first issues.
On the other hand, its been ready to implement for almost a month now 😅

**Comment by peth-yursick** [comment]
Its not urgent until @alalonde fixes the onboarding bot but its fairly high impact

**Comment by vidvidvid** [comment]
> One one hand, I'd leave this to newcomers because it's a good first issue & we've received feedback from newcomers that there aren't enough meaningful good first issues. On the other hand, its been ready to implement for almost a month now 😅

Good point, I agree. I can leave it for now and if it becomes urgent (or whenever you think it's been enough of waiting), just ping me and i'll jump on it, provided the design is rdy.

**Comment by peth-yursick** [comment]
> > One one hand, I'd leave this to newcomers because it's a good first issue & we've received feedback from newcomers that there aren't enough meaningful good first issues. On the other hand, its been ready to implement for almost a month now 😅
> 
> Good point, I agree. I can leave it for now and if it becomes urgent (or whenever you think it's been enough of waiting), just ping me and i'll jump on it, provided the design is rdy.

Looks like nobody else is jumping on it & its kiiind of urgent (I want to continue onboarding guilds but feels lame to send them the notion page first & then this out of date page second when it could be 1 link with all info).
The copy is finished & I think we can put it on as a text page. We should have a properly design landing for guilds at some point but I think this is enough for now 🤷‍♂️

**Comment by peth-yursick** [comment]
are you sure this is closed @mquellhorst ?
opening https://my.metagame.wtf/join/guild still gives the old page..

**Comment by vidvidvid** [comment]
@peth-yursick once it's merged to `develop` branch it doesn't go live yet - `develop` has to be merged into `master` in order for it to go live.
